/**
 * Catalogue Filtering System
 */
class CatalogueFilter {
    constructor() {
        this.products = [
            { id: 1, name: 'Tableau Abstrait', category: 'Peinture', price: 150, artist: 'Marie Dupont', image: '🎨' },
            { id: 2, name: 'Sculpture Moderne', category: 'Sculpture', price: 300, artist: 'Jean Martin', image: '🗿' },
            { id: 3, name: 'Photographie Urbaine', category: 'Photographie', price: 120, artist: 'Sophia Laurent', image: '📷' },
            { id: 4, name: 'Dessin Figuratif', category: 'Dessin', price: 80, artist: 'Pierre Durand', image: '✏️' }
        ];
        this.setupFilters();\n    }\n\n    setupFilters() {\n        const searchInput = document.getElementById('searchInput');\n        const categoryFilter = document.getElementById('categoryFilter');\n        const priceFilter = document.getElementById('priceFilter');\n\n        if (searchInput) searchInput.addEventListener('keyup', () => this.applyFilters());\n        if (categoryFilter) categoryFilter.addEventListener('change', () => this.applyFilters());\n        if (priceFilter) priceFilter.addEventListener('change', () => this.applyFilters());\n    }\n\n    applyFilters() {\n        const search = (document.getElementById('searchInput')?.value || '').toLowerCase();\n        const category = document.getElementById('categoryFilter')?.value || 'all';\n        const price = document.getElementById('priceFilter')?.value || 'all';\n\n        let filtered = this.products.filter(product => {\n            // Search filter\n            if (search && !product.name.toLowerCase().includes(search)) return false;\n            \n            // Category filter\n            if (category !== 'all' && product.category !== category) return false;\n            \n            // Price filter\n            if (price === 'low' && product.price > 100) return false;\n            if (price === 'medium' && (product.price <= 100 || product.price > 250)) return false;\n            if (price === 'high' && product.price <= 250) return false;\n            \n            return true;\n        });\n\n        this.displayResults(filtered);\n    }\n\n    displayResults(products) {\n        const resultsContainer = document.getElementById('filteredResults');\n        if (!resultsContainer) return;\n\n        if (products.length === 0) {\n            resultsContainer.innerHTML = '<p style=\"text-align: center; color: #b0b0b0; grid-column: 1 / -1;\">Aucune œuvre ne correspond à votre recherche</p>';\n            return;\n        }\n\n        resultsContainer.innerHTML = products.map(product => `\n            <div class=\"card\">\n                <div class=\"card-image\">${product.image}</div>\n                <div class=\"card-content\">\n                    <h3>${product.name}</h3>\n                    <p>${product.category} par ${product.artist}</p>\n                    <div class=\"price\">${product.price}€</div>\n                    <button class=\"btn btn-primary\" onclick=\"addToCart(${product.id})\" style=\"width: 100%; margin-top: 1rem;\">🛒 Ajouter</button>\n                </div>\n            </div>\n        `).join('');\n    }\n}\n\n// Initialize on page load\ndocument.addEventListener('DOMContentLoaded', () => {\n    if (document.getElementById('cataloguePage')) {\n        new CatalogueFilter();\n    }\n});\n","message":"Create catalogue filtering system","owner":"juanjunior21","path":"frontend/js/catalogue.js","repo":"djounagalerie"}
